"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var User_controller_1 = __importDefault(require("./controllers/User.controller"));
var Form_controller_1 = __importDefault(require("./controllers/Form.controller"));
var Auth_controller_1 = __importDefault(require("./controllers/Auth.controller"));
var routes = express_1.Router();
routes.get('/api/users', User_controller_1.default.find);
routes.post('/api/users', User_controller_1.default.create);
routes.get('/api/forms', Form_controller_1.default.find);
routes.post('/api/forms', Form_controller_1.default.create);
routes.get('/auths', Auth_controller_1.default.find);
routes.get('/auths/findOnes', Auth_controller_1.default.findOne);
routes.post('/auths', Auth_controller_1.default.create);
routes.delete('/auths', Auth_controller_1.default.delete);
routes.put('/auths', Auth_controller_1.default.update);
exports.default = routes;
